# Generated by Django 4.1 on 2022-08-12 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserForename', models.CharField(max_length=100, null=True)),
                ('UserSurname', models.CharField(max_length=100, null=True)),
                ('UserEmail', models.CharField(max_length=100)),
                ('UserJoinDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('SensorId', models.AutoField(primary_key=True, serialize=False)),
                ('SensorName', models.CharField(max_length=100)),
                ('SensorLocation', models.CharField(max_length=100, null=True)),
                ('SetupDate', models.DateField(null=True)),
                ('UserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('ReadingId', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ReadTime', models.DateTimeField(auto_now_add=True)),
                ('SensorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.sensor')),
            ],
        ),
    ]
