# Generated by Django 4.1 on 2022-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserJoinDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
