# Generated by Django 4.1 on 2022-08-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_alter_sensor_setupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='SensorUnit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
