# Generated by Django 4.1 on 2022-08-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_rename_value_reading_readingvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertProfile',
            fields=[
                ('AlertProfileId', models.AutoField(primary_key=True, serialize=False)),
                ('HighThreshold', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('TargetValue', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('LowThreshold', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('AlertEmail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='AlertProfileId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.alertprofile'),
        ),
    ]
