# Generated by Django 4.1 on 2022-08-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertprofile',
            name='AlertProfileName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
