# Generated by Django 4.1 on 2022-08-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0008_alertprofile_alertprofilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='UserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.user'),
        ),
    ]
